version: "3.8"

services:
  postgres:
    container_name: ${POSTGRES_HOST}
    env_file:
      - ./configs/secrets/postgres.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - cars_dbdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s

  dev_postgres:
    container_name: cars_devdb
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    ports:
      - "6543:5432"
    volumes:
      - cars_dev_dbdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U user -d test'"
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 3s

networks:
  backend:
    driver: bridge

volumes:
  cars_dbdata:
    driver: local
  cars_dev_dbdata:
    driver: local