version: '3'

includes:
  go: tasks/go.tasks.yml
  atlas: tasks/atlas.tasks.yml
  install: tasks/install.tasks.yml

silent: false

tasks:
  default:
    label: "liveserver"
    aliases: 
      - "liveserver"
    cmds:
      - echo "Starting liveserver..."
      - air -c .air.toml run ./cmd/server/main.go
    desc: "Starts the liveserver"
  install-tools:
    deps:
      - "install:air"



