version: '3'

includes:
  go: tasks/go.tasks.yml
  atlas: tasks/atlas.tasks.yml
  install: tasks/install.tasks.yml
  docker: tasks/docker.tasks.yml
  ent: tasks/ent.tasks.yml

silent: false

tasks:
  default:
    dotenv:
      - "./configs/secrets/postgres.env"
    label: "liveserver"
    aliases: 
      - "liveserver"
    cmds:
      - echo "Starting liveserver..."
      - air -c .air.toml run ./cmd/server/main.go
    desc: "Starts the liveserver"
  install-tools:
    deps:
      - "install:air"
  seed:
    dotenv:
      - "./configs/secrets/postgres.env"
    cmds:
      - echo "Seeding database..."
      - go run ./cmd/seed
    silent: true




