version: "3"

vars:
  PATH_TO_DOCKERFILE: "./docker/Dockerfile"


tasks:
  build-image:
    desc: "Builds the docker image"
    cmds:
      - 'read -p "Enter image tag: " imageTag;
        docker build -t $imageTag -f {{ .PATH_TO_DOCKERFILE }} .'