version: "3"

vars:
  PATH_TO_DOCKERFILE: "./docker/Dockerfile"
  IMAGE_NAME: "yawnak/fuelrecordcrud"


tasks:
  build-image:
    desc: "Builds the docker image"
    cmds:
      - 'read -p "Enter image tag: " imageTag;
        docker build -t "{{.IMAGE_NAME}}:$imageTag" -f {{ .PATH_TO_DOCKERFILE }} .'