// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CarsColumns holds the columns for the "cars" table.
	CarsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "car_id", Type: field.TypeUUID},
		{Name: "make", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "year", Type: field.TypeInt8},
	}
	// CarsTable holds the schema information for the "cars" table.
	CarsTable = &schema.Table{
		Name:       "cars",
		Columns:    CarsColumns,
		PrimaryKey: []*schema.Column{CarsColumns[0]},
	}
	// FuelRecordsColumns holds the columns for the "fuel_records" table.
	FuelRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// FuelRecordsTable holds the schema information for the "fuel_records" table.
	FuelRecordsTable = &schema.Table{
		Name:       "fuel_records",
		Columns:    FuelRecordsColumns,
		PrimaryKey: []*schema.Column{FuelRecordsColumns[0]},
	}
	// OdometerRecordsColumns holds the columns for the "odometer_records" table.
	OdometerRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// OdometerRecordsTable holds the schema information for the "odometer_records" table.
	OdometerRecordsTable = &schema.Table{
		Name:       "odometer_records",
		Columns:    OdometerRecordsColumns,
		PrimaryKey: []*schema.Column{OdometerRecordsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CarsTable,
		FuelRecordsTable,
		OdometerRecordsTable,
	}
)

func init() {
}
