// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yawnak/fuel-record-crud/ent/fuelrecord"
	"github.com/yawnak/fuel-record-crud/ent/predicate"
)

// FuelRecordQuery is the builder for querying FuelRecord entities.
type FuelRecordQuery struct {
	config
	ctx        *QueryContext
	order      []fuelrecord.OrderOption
	inters     []Interceptor
	predicates []predicate.FuelRecord
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FuelRecordQuery builder.
func (frq *FuelRecordQuery) Where(ps ...predicate.FuelRecord) *FuelRecordQuery {
	frq.predicates = append(frq.predicates, ps...)
	return frq
}

// Limit the number of records to be returned by this query.
func (frq *FuelRecordQuery) Limit(limit int) *FuelRecordQuery {
	frq.ctx.Limit = &limit
	return frq
}

// Offset to start from.
func (frq *FuelRecordQuery) Offset(offset int) *FuelRecordQuery {
	frq.ctx.Offset = &offset
	return frq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (frq *FuelRecordQuery) Unique(unique bool) *FuelRecordQuery {
	frq.ctx.Unique = &unique
	return frq
}

// Order specifies how the records should be ordered.
func (frq *FuelRecordQuery) Order(o ...fuelrecord.OrderOption) *FuelRecordQuery {
	frq.order = append(frq.order, o...)
	return frq
}

// First returns the first FuelRecord entity from the query.
// Returns a *NotFoundError when no FuelRecord was found.
func (frq *FuelRecordQuery) First(ctx context.Context) (*FuelRecord, error) {
	nodes, err := frq.Limit(1).All(setContextOp(ctx, frq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fuelrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (frq *FuelRecordQuery) FirstX(ctx context.Context) *FuelRecord {
	node, err := frq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FuelRecord ID from the query.
// Returns a *NotFoundError when no FuelRecord ID was found.
func (frq *FuelRecordQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = frq.Limit(1).IDs(setContextOp(ctx, frq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fuelrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (frq *FuelRecordQuery) FirstIDX(ctx context.Context) int {
	id, err := frq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FuelRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FuelRecord entity is found.
// Returns a *NotFoundError when no FuelRecord entities are found.
func (frq *FuelRecordQuery) Only(ctx context.Context) (*FuelRecord, error) {
	nodes, err := frq.Limit(2).All(setContextOp(ctx, frq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fuelrecord.Label}
	default:
		return nil, &NotSingularError{fuelrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (frq *FuelRecordQuery) OnlyX(ctx context.Context) *FuelRecord {
	node, err := frq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FuelRecord ID in the query.
// Returns a *NotSingularError when more than one FuelRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (frq *FuelRecordQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = frq.Limit(2).IDs(setContextOp(ctx, frq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fuelrecord.Label}
	default:
		err = &NotSingularError{fuelrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (frq *FuelRecordQuery) OnlyIDX(ctx context.Context) int {
	id, err := frq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FuelRecords.
func (frq *FuelRecordQuery) All(ctx context.Context) ([]*FuelRecord, error) {
	ctx = setContextOp(ctx, frq.ctx, "All")
	if err := frq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FuelRecord, *FuelRecordQuery]()
	return withInterceptors[[]*FuelRecord](ctx, frq, qr, frq.inters)
}

// AllX is like All, but panics if an error occurs.
func (frq *FuelRecordQuery) AllX(ctx context.Context) []*FuelRecord {
	nodes, err := frq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FuelRecord IDs.
func (frq *FuelRecordQuery) IDs(ctx context.Context) (ids []int, err error) {
	if frq.ctx.Unique == nil && frq.path != nil {
		frq.Unique(true)
	}
	ctx = setContextOp(ctx, frq.ctx, "IDs")
	if err = frq.Select(fuelrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (frq *FuelRecordQuery) IDsX(ctx context.Context) []int {
	ids, err := frq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (frq *FuelRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, frq.ctx, "Count")
	if err := frq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, frq, querierCount[*FuelRecordQuery](), frq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (frq *FuelRecordQuery) CountX(ctx context.Context) int {
	count, err := frq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (frq *FuelRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, frq.ctx, "Exist")
	switch _, err := frq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (frq *FuelRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := frq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FuelRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (frq *FuelRecordQuery) Clone() *FuelRecordQuery {
	if frq == nil {
		return nil
	}
	return &FuelRecordQuery{
		config:     frq.config,
		ctx:        frq.ctx.Clone(),
		order:      append([]fuelrecord.OrderOption{}, frq.order...),
		inters:     append([]Interceptor{}, frq.inters...),
		predicates: append([]predicate.FuelRecord{}, frq.predicates...),
		// clone intermediate query.
		sql:  frq.sql.Clone(),
		path: frq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (frq *FuelRecordQuery) GroupBy(field string, fields ...string) *FuelRecordGroupBy {
	frq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FuelRecordGroupBy{build: frq}
	grbuild.flds = &frq.ctx.Fields
	grbuild.label = fuelrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (frq *FuelRecordQuery) Select(fields ...string) *FuelRecordSelect {
	frq.ctx.Fields = append(frq.ctx.Fields, fields...)
	sbuild := &FuelRecordSelect{FuelRecordQuery: frq}
	sbuild.label = fuelrecord.Label
	sbuild.flds, sbuild.scan = &frq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FuelRecordSelect configured with the given aggregations.
func (frq *FuelRecordQuery) Aggregate(fns ...AggregateFunc) *FuelRecordSelect {
	return frq.Select().Aggregate(fns...)
}

func (frq *FuelRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range frq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, frq); err != nil {
				return err
			}
		}
	}
	for _, f := range frq.ctx.Fields {
		if !fuelrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if frq.path != nil {
		prev, err := frq.path(ctx)
		if err != nil {
			return err
		}
		frq.sql = prev
	}
	return nil
}

func (frq *FuelRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FuelRecord, error) {
	var (
		nodes = []*FuelRecord{}
		_spec = frq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FuelRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FuelRecord{config: frq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, frq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (frq *FuelRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := frq.querySpec()
	_spec.Node.Columns = frq.ctx.Fields
	if len(frq.ctx.Fields) > 0 {
		_spec.Unique = frq.ctx.Unique != nil && *frq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, frq.driver, _spec)
}

func (frq *FuelRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(fuelrecord.Table, fuelrecord.Columns, sqlgraph.NewFieldSpec(fuelrecord.FieldID, field.TypeInt))
	_spec.From = frq.sql
	if unique := frq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if frq.path != nil {
		_spec.Unique = true
	}
	if fields := frq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fuelrecord.FieldID)
		for i := range fields {
			if fields[i] != fuelrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := frq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := frq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := frq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := frq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (frq *FuelRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(frq.driver.Dialect())
	t1 := builder.Table(fuelrecord.Table)
	columns := frq.ctx.Fields
	if len(columns) == 0 {
		columns = fuelrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if frq.sql != nil {
		selector = frq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if frq.ctx.Unique != nil && *frq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range frq.predicates {
		p(selector)
	}
	for _, p := range frq.order {
		p(selector)
	}
	if offset := frq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := frq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FuelRecordGroupBy is the group-by builder for FuelRecord entities.
type FuelRecordGroupBy struct {
	selector
	build *FuelRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (frgb *FuelRecordGroupBy) Aggregate(fns ...AggregateFunc) *FuelRecordGroupBy {
	frgb.fns = append(frgb.fns, fns...)
	return frgb
}

// Scan applies the selector query and scans the result into the given value.
func (frgb *FuelRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frgb.build.ctx, "GroupBy")
	if err := frgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FuelRecordQuery, *FuelRecordGroupBy](ctx, frgb.build, frgb, frgb.build.inters, v)
}

func (frgb *FuelRecordGroupBy) sqlScan(ctx context.Context, root *FuelRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(frgb.fns))
	for _, fn := range frgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*frgb.flds)+len(frgb.fns))
		for _, f := range *frgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*frgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FuelRecordSelect is the builder for selecting fields of FuelRecord entities.
type FuelRecordSelect struct {
	*FuelRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (frs *FuelRecordSelect) Aggregate(fns ...AggregateFunc) *FuelRecordSelect {
	frs.fns = append(frs.fns, fns...)
	return frs
}

// Scan applies the selector query and scans the result into the given value.
func (frs *FuelRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, frs.ctx, "Select")
	if err := frs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FuelRecordQuery, *FuelRecordSelect](ctx, frs.FuelRecordQuery, frs, frs.inters, v)
}

func (frs *FuelRecordSelect) sqlScan(ctx context.Context, root *FuelRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(frs.fns))
	for _, fn := range frs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*frs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
