// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yawnak/fuel-record-crud/ent/fuelrecord"
	"github.com/yawnak/fuel-record-crud/ent/predicate"
)

// FuelRecordDelete is the builder for deleting a FuelRecord entity.
type FuelRecordDelete struct {
	config
	hooks    []Hook
	mutation *FuelRecordMutation
}

// Where appends a list predicates to the FuelRecordDelete builder.
func (frd *FuelRecordDelete) Where(ps ...predicate.FuelRecord) *FuelRecordDelete {
	frd.mutation.Where(ps...)
	return frd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (frd *FuelRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, frd.sqlExec, frd.mutation, frd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (frd *FuelRecordDelete) ExecX(ctx context.Context) int {
	n, err := frd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (frd *FuelRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(fuelrecord.Table, sqlgraph.NewFieldSpec(fuelrecord.FieldID, field.TypeInt))
	if ps := frd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, frd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	frd.mutation.done = true
	return affected, err
}

// FuelRecordDeleteOne is the builder for deleting a single FuelRecord entity.
type FuelRecordDeleteOne struct {
	frd *FuelRecordDelete
}

// Where appends a list predicates to the FuelRecordDelete builder.
func (frdo *FuelRecordDeleteOne) Where(ps ...predicate.FuelRecord) *FuelRecordDeleteOne {
	frdo.frd.mutation.Where(ps...)
	return frdo
}

// Exec executes the deletion query.
func (frdo *FuelRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := frdo.frd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fuelrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (frdo *FuelRecordDeleteOne) ExecX(ctx context.Context) {
	if err := frdo.Exec(ctx); err != nil {
		panic(err)
	}
}
