// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/yawnak/fuel-record-crud/ent/car"
	"github.com/yawnak/fuel-record-crud/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	carFields := schema.Car{}.Fields()
	_ = carFields
	// carDescMake is the schema descriptor for make field.
	carDescMake := carFields[1].Descriptor()
	// car.MakeValidator is a validator for the "make" field. It is called by the builders before save.
	car.MakeValidator = carDescMake.Validators[0].(func(string) error)
	// carDescModel is the schema descriptor for model field.
	carDescModel := carFields[2].Descriptor()
	// car.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	car.ModelValidator = carDescModel.Validators[0].(func(string) error)
	// carDescYear is the schema descriptor for year field.
	carDescYear := carFields[3].Descriptor()
	// car.YearValidator is a validator for the "year" field. It is called by the builders before save.
	car.YearValidator = carDescYear.Validators[0].(func(int8) error)
}
