// Code generated by ent, DO NOT EDIT.

package odometerrecord

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the odometerrecord type in the database.
	Label = "odometer_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the odometerrecord in the database.
	Table = "odometer_records"
)

// Columns holds all SQL columns for odometerrecord fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the OdometerRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}
