// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Car is the predicate function for car builders.
type Car func(*sql.Selector)

// FuelRecord is the predicate function for fuelrecord builders.
type FuelRecord func(*sql.Selector)

// OdometerRecord is the predicate function for odometerrecord builders.
type OdometerRecord func(*sql.Selector)
